
import MyContext from "@/Helper/Context";
import "./globals.css";


export const metadata = {
  title: "Shyammus App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white"><MyContext>
        {children}
        </MyContext></body>
    </html>
  );
}
